# Generated by Django 5.0.1 on 2025-11-16 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('owner', 'Owner'), ('admin', 'Admin'), ('student', 'Student')], default='student', help_text='User role: admin or student', max_length=10),
        ),
    ]
