# Generated by Django 5.2.9 on 2026-01-30 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_remove_owner_role"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="is_vip",
            field=models.BooleanField(
                default=False, help_text="Whether user has VIP access to all variants"
            ),
        ),
    ]
