# Generated by Django 5.0.1 on 2025-11-16 09:31

import django.core.validators
import django.db.models.deletion
import exams.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Variant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Variant name', max_length=200)),
                ('code', models.CharField(default=exams.models.generate_variant_code, help_text='Unique 6-digit code', max_length=6, unique=True)),
                ('duration_minutes', models.PositiveIntegerField(help_text='Test duration in minutes', validators=[django.core.validators.MinValueValidator(1)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_variants', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'variant',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TestFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_type', models.CharField(choices=[('reading', 'Reading'), ('listening', 'Listening'), ('writing', 'Writing')], help_text='Type of test file', max_length=20)),
                ('task_number', models.PositiveIntegerField(blank=True, help_text='Task number for writing section (1 or 2), null for other sections', null=True)),
                ('file', models.FileField(help_text='Test file (PDF, DOCX, etc.)', upload_to='test_files/%Y/%m/%d/')),
                ('audio_file', models.FileField(blank=True, help_text='Audio file for listening section (optional)', null=True, upload_to='audio_files/%Y/%m/%d/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_files', to='exams.variant')),
            ],
            options={
                'db_table': 'test_file',
                'unique_together': {('variant', 'file_type', 'task_number')},
            },
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.CharField(choices=[('reading', 'Reading'), ('listening', 'Listening')], help_text='Section type', max_length=20)),
                ('question_number', models.PositiveIntegerField(help_text='Question number', validators=[django.core.validators.MinValueValidator(1)])),
                ('correct_answer', models.CharField(help_text='Correct answer (e.g., A, B, C, D, TRUE, FALSE, etc.)', max_length=10)),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='exams.variant')),
            ],
            options={
                'db_table': 'answer',
                'ordering': ['section', 'question_number'],
                'unique_together': {('variant', 'section', 'question_number')},
            },
        ),
    ]
