# Generated by Django 5.0.1 on 2026-01-19 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("exams", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="answer",
            name="alternative_answers",
            field=models.JSONField(
                blank=True,
                help_text="Alternative acceptable answers (array of strings)",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="answer",
            name="case_sensitive",
            field=models.BooleanField(
                default=False,
                help_text="Whether answer matching should be case-sensitive",
            ),
        ),
        migrations.AddField(
            model_name="testfile",
            name="duration_minutes",
            field=models.PositiveIntegerField(
                blank=True, help_text="Duration for this section in minutes", null=True
            ),
        ),
        migrations.AddField(
            model_name="testfile",
            name="questions_data",
            field=models.JSONField(
                blank=True,
                help_text="Structured question data in JSON format",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="answer",
            name="correct_answer",
            field=models.CharField(
                help_text="Correct answer (e.g., A, B, C, D, TRUE, FALSE, etc.)",
                max_length=200,
            ),
        ),
    ]
