# Generated by Django 5.2.9 on 2026-01-24 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("exams", "0002_add_questions_data_fields"),
    ]

    operations = [
        migrations.AlterField(
            model_name="testfile",
            name="file_type",
            field=models.CharField(
                choices=[
                    ("reading", "Reading"),
                    ("listening", "Listening"),
                    ("writing", "Writing"),
                    ("speaking", "Speaking"),
                ],
                help_text="Type of test file",
                max_length=20,
            ),
        ),
    ]
