# Generated by Django 5.2.9 on 2026-01-27 16:11

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("exams", "0003_alter_testfile_file_type"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MockTest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "test_id",
                    models.CharField(
                        help_text="Unique 6-digit test ID", max_length=6, unique=True
                    ),
                ),
                (
                    "variant_strategy",
                    models.CharField(
                        choices=[
                            ("same", "Same variant for all students"),
                            ("unique", "Unique variant for each student"),
                        ],
                        help_text="How variants are distributed to students",
                        max_length=10,
                    ),
                ),
                (
                    "selected_variants",
                    models.JSONField(
                        blank=True,
                        help_text='Pre-selected variants for "same" strategy',
                        null=True,
                    ),
                ),
                (
                    "duration_minutes",
                    models.PositiveIntegerField(
                        default=180,
                        help_text="Total test duration in minutes",
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_mock_tests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "mock_test",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="StudentTestSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "assigned_variants",
                    models.JSONField(
                        help_text="Assigned variant files for this student"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("waiting", "Waiting"),
                            ("in_progress", "In Progress"),
                            ("completed", "Completed"),
                        ],
                        default="waiting",
                        max_length=20,
                    ),
                ),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "current_section",
                    models.CharField(
                        blank=True,
                        help_text="Current section student is on",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "mock_test",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="student_sessions",
                        to="exams.mocktest",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="test_sessions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "student_test_session",
                "ordering": ["-started_at"],
                "unique_together": {("mock_test", "student")},
            },
        ),
    ]
