# Generated by Django 5.0.1 on 2025-11-16 09:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('exams', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('in_progress', 'In Progress'), ('submitted', 'Submitted'), ('graded', 'Graded')], default='in_progress', max_length=20)),
                ('start_time', models.DateTimeField(auto_now_add=True)),
                ('submission_time', models.DateTimeField(blank=True, null=True)),
                ('time_remaining_seconds', models.PositiveIntegerField(blank=True, help_text='Remaining time in seconds when test was submitted', null=True)),
                ('student', models.ForeignKey(limit_choices_to={'role': 'student'}, on_delete=django.db.models.deletion.CASCADE, related_name='test_attempts', to=settings.AUTH_USER_MODEL)),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_tests', to='exams.variant')),
            ],
            options={
                'db_table': 'student_test',
                'ordering': ['-start_time'],
                'unique_together': {('student', 'variant')},
            },
        ),
        migrations.CreateModel(
            name='TestResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('listening_score', models.DecimalField(blank=True, decimal_places=2, help_text='Listening score (0-9)', max_digits=5, null=True)),
                ('reading_score', models.DecimalField(blank=True, decimal_places=2, help_text='Reading score (0-9)', max_digits=5, null=True)),
                ('writing_score', models.DecimalField(blank=True, decimal_places=2, help_text='Writing score (0-9)', max_digits=5, null=True)),
                ('writing_task1_score', models.DecimalField(blank=True, decimal_places=2, help_text='Writing Task 1 score (0-9)', max_digits=5, null=True)),
                ('writing_task2_score', models.DecimalField(blank=True, decimal_places=2, help_text='Writing Task 2 score (0-9)', max_digits=5, null=True)),
                ('overall_score', models.DecimalField(blank=True, decimal_places=2, help_text='Overall band score', max_digits=5, null=True)),
                ('listening_breakdown', models.JSONField(blank=True, help_text='Detailed listening score breakdown', null=True)),
                ('reading_breakdown', models.JSONField(blank=True, help_text='Detailed reading score breakdown', null=True)),
                ('writing_breakdown', models.JSONField(blank=True, help_text='Detailed writing score breakdown (AI evaluation)', null=True)),
                ('graded_at', models.DateTimeField(auto_now_add=True)),
                ('graded_by', models.ForeignKey(blank=True, limit_choices_to={'role': 'admin'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='graded_tests', to=settings.AUTH_USER_MODEL)),
                ('student_test', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='result', to='student_portal.studenttest')),
            ],
            options={
                'db_table': 'test_result',
                'ordering': ['-graded_at'],
            },
        ),
        migrations.CreateModel(
            name='TestQueue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_code', models.CharField(help_text='6-digit test code entered by student', max_length=6)),
                ('status', models.CharField(choices=[('waiting', 'Waiting'), ('assigned', 'Assigned'), ('preparation', 'Preparation'), ('started', 'Started')], default='waiting', max_length=20)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_at', models.DateTimeField(blank=True, null=True)),
                ('preparation_started_at', models.DateTimeField(blank=True, null=True)),
                ('assigned_variant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='queue_assignments', to='exams.variant')),
                ('student', models.ForeignKey(limit_choices_to={'role': 'student'}, on_delete=django.db.models.deletion.CASCADE, related_name='queue_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'test_queue',
                'ordering': ['joined_at'],
                'unique_together': {('student', 'test_code')},
            },
        ),
        migrations.CreateModel(
            name='TestResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.CharField(choices=[('reading', 'Reading'), ('listening', 'Listening'), ('writing', 'Writing')], help_text='Section type', max_length=20)),
                ('question_number', models.PositiveIntegerField(blank=True, help_text='Question number (null for writing section)', null=True)),
                ('answer', models.TextField(help_text='Student answer')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student_test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='student_portal.studenttest')),
            ],
            options={
                'db_table': 'test_response',
                'ordering': ['section', 'question_number'],
                'unique_together': {('student_test', 'section', 'question_number')},
            },
        ),
    ]
