# Generated by Django 5.2.9 on 2026-01-24 11:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("student_portal", "0003_add_started_at_to_testqueue"),
    ]

    operations = [
        migrations.AddField(
            model_name="testresult",
            name="speaking_breakdown",
            field=models.JSONField(
                blank=True,
                help_text="Detailed speaking score breakdown (AI evaluation)",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="testresult",
            name="speaking_score",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Speaking score (0-9)",
                max_digits=5,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="testresponse",
            name="section",
            field=models.CharField(
                choices=[
                    ("reading", "Reading"),
                    ("listening", "Listening"),
                    ("writing", "Writing"),
                    ("speaking", "Speaking"),
                ],
                help_text="Section type",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="SpeakingResponse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "part_number",
                    models.PositiveIntegerField(
                        help_text="Speaking part number (1, 2, or 3)"
                    ),
                ),
                (
                    "question_number",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Question number within the part (for Part 1 and 3, null for Part 2)",
                        null=True,
                    ),
                ),
                (
                    "audio_file",
                    models.FileField(
                        help_text="Student audio recording",
                        upload_to="speaking_audio/%Y/%m/%d/",
                    ),
                ),
                (
                    "transcribed_text",
                    models.TextField(
                        blank=True, help_text="Transcribed text from audio", null=True
                    ),
                ),
                (
                    "transcription_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        help_text="Status of transcription process",
                        max_length=20,
                    ),
                ),
                (
                    "transcription_metadata",
                    models.JSONField(
                        blank=True,
                        help_text="Additional transcription data (language, duration, etc.)",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "student_test",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="speaking_responses",
                        to="student_portal.studenttest",
                    ),
                ),
            ],
            options={
                "db_table": "speaking_response",
                "ordering": ["part_number", "question_number"],
                "unique_together": {("student_test", "part_number", "question_number")},
            },
        ),
    ]
